### ISSUE TITLE
$RegEx placeholder not working

### ISSUE THREAD

**Issue by SueGK** [fbgallet/roam-extension-find-replace#2]
I am having trouble using the $RegEx or $1 placeholder in my extension's replace function. It was working before, but now it doesn't seem to be doing anything. I'm not sure if there are any conflicts with other extensions that I have installed. What can I do to troubleshoot this issue?
![CleanShot 2023-02-24 at 05 14 04](https://user-images.githubusercontent.com/71711489/221098558-727528fd-9502-4248-bd3a-33bf2be5f131.gif)

**Comment by fbgallet** [comment]
Thanks for report, @SueGK !
It was broken, indeed. Its fixed in the new submitted version (but review by Roam Team can take some time, 1 or 2 weeks)

**Comment by fbgallet** [comment]
@SueGK , the update is published.
